/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as RedirectRouteImport } from './pages/redirect'
import { Route as BillingRouteImport } from './pages/billing'
import { Route as LayoutRouteImport } from './pages/_layout'
import { Route as AuthRouteImport } from './pages/_auth'
import { Route as IndexRouteImport } from './pages/index'
import { Route as PublicDomainRouteImport } from './pages/public/$domain'
import { Route as OnboardingWaitingRouteImport } from './pages/onboarding/waiting'
import { Route as OnboardingProjectRouteImport } from './pages/onboarding/project'
import { Route as OnboardingPricingRouteImport } from './pages/onboarding/pricing'
import { Route as OnboardingOrganizationRouteImport } from './pages/onboarding/organization'
import { Route as OOrganizationIdRouteImport } from './pages/o/$organizationId'
import { Route as MailUnsubscribeRouteImport } from './pages/mail/unsubscribe'
import { Route as InviteTokenRouteImport } from './pages/invite/$token'
import { Route as AuthSignupRouteImport } from './pages/_auth/signup'
import { Route as AuthResetPasswordRouteImport } from './pages/_auth/reset-password'
import { Route as AuthLoginRouteImport } from './pages/_auth/login'
import { Route as LayoutPProjectIdRouteImport } from './pages/_layout/p/$projectId'
import { Route as LayoutPProjectIdIndexRouteImport } from './pages/_layout/p/$projectId/index'
import { Route as LayoutPProjectIdUsersIndexRouteImport } from './pages/_layout/p/$projectId/users/index'
import { Route as LayoutPProjectIdSettingsIndexRouteImport } from './pages/_layout/p/$projectId/settings/index'
import { Route as LayoutPProjectIdFunnelsIndexRouteImport } from './pages/_layout/p/$projectId/funnels/index'
import { Route as LayoutPProjectIdEventsIndexRouteImport } from './pages/_layout/p/$projectId/events/index'
import { Route as LayoutPProjectIdUsersUserIdRouteImport } from './pages/_layout/p/$projectId/users/$userId'
import { Route as LayoutPProjectIdUserIdentifierRouteImport } from './pages/_layout/p/$projectId/user/$identifier'
import { Route as LayoutPProjectIdFunnelsFunnelIdRouteImport } from './pages/_layout/p/$projectId/funnels/$funnelId'

const RedirectRoute = RedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicDomainRoute = PublicDomainRouteImport.update({
  id: '/public/$domain',
  path: '/public/$domain',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingWaitingRoute = OnboardingWaitingRouteImport.update({
  id: '/onboarding/waiting',
  path: '/onboarding/waiting',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingProjectRoute = OnboardingProjectRouteImport.update({
  id: '/onboarding/project',
  path: '/onboarding/project',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingPricingRoute = OnboardingPricingRouteImport.update({
  id: '/onboarding/pricing',
  path: '/onboarding/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingOrganizationRoute = OnboardingOrganizationRouteImport.update({
  id: '/onboarding/organization',
  path: '/onboarding/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const OOrganizationIdRoute = OOrganizationIdRouteImport.update({
  id: '/o/$organizationId',
  path: '/o/$organizationId',
  getParentRoute: () => rootRouteImport,
} as any)
const MailUnsubscribeRoute = MailUnsubscribeRouteImport.update({
  id: '/mail/unsubscribe',
  path: '/mail/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const LayoutPProjectIdRoute = LayoutPProjectIdRouteImport.update({
  id: '/p/$projectId',
  path: '/p/$projectId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPProjectIdIndexRoute = LayoutPProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutPProjectIdRoute,
} as any)
const LayoutPProjectIdUsersIndexRoute =
  LayoutPProjectIdUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => LayoutPProjectIdRoute,
  } as any)
const LayoutPProjectIdSettingsIndexRoute =
  LayoutPProjectIdSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => LayoutPProjectIdRoute,
  } as any)
const LayoutPProjectIdFunnelsIndexRoute =
  LayoutPProjectIdFunnelsIndexRouteImport.update({
    id: '/funnels/',
    path: '/funnels/',
    getParentRoute: () => LayoutPProjectIdRoute,
  } as any)
const LayoutPProjectIdEventsIndexRoute =
  LayoutPProjectIdEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => LayoutPProjectIdRoute,
  } as any)
const LayoutPProjectIdUsersUserIdRoute =
  LayoutPProjectIdUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => LayoutPProjectIdRoute,
  } as any)
const LayoutPProjectIdUserIdentifierRoute =
  LayoutPProjectIdUserIdentifierRouteImport.update({
    id: '/user/$identifier',
    path: '/user/$identifier',
    getParentRoute: () => LayoutPProjectIdRoute,
  } as any)
const LayoutPProjectIdFunnelsFunnelIdRoute =
  LayoutPProjectIdFunnelsFunnelIdRouteImport.update({
    id: '/funnels/$funnelId',
    path: '/funnels/$funnelId',
    getParentRoute: () => LayoutPProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/redirect': typeof RedirectRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/invite/$token': typeof InviteTokenRoute
  '/mail/unsubscribe': typeof MailUnsubscribeRoute
  '/o/$organizationId': typeof OOrganizationIdRoute
  '/onboarding/organization': typeof OnboardingOrganizationRoute
  '/onboarding/pricing': typeof OnboardingPricingRoute
  '/onboarding/project': typeof OnboardingProjectRoute
  '/onboarding/waiting': typeof OnboardingWaitingRoute
  '/public/$domain': typeof PublicDomainRoute
  '/p/$projectId': typeof LayoutPProjectIdRouteWithChildren
  '/p/$projectId/': typeof LayoutPProjectIdIndexRoute
  '/p/$projectId/funnels/$funnelId': typeof LayoutPProjectIdFunnelsFunnelIdRoute
  '/p/$projectId/user/$identifier': typeof LayoutPProjectIdUserIdentifierRoute
  '/p/$projectId/users/$userId': typeof LayoutPProjectIdUsersUserIdRoute
  '/p/$projectId/events': typeof LayoutPProjectIdEventsIndexRoute
  '/p/$projectId/funnels': typeof LayoutPProjectIdFunnelsIndexRoute
  '/p/$projectId/settings': typeof LayoutPProjectIdSettingsIndexRoute
  '/p/$projectId/users': typeof LayoutPProjectIdUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/redirect': typeof RedirectRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/invite/$token': typeof InviteTokenRoute
  '/mail/unsubscribe': typeof MailUnsubscribeRoute
  '/o/$organizationId': typeof OOrganizationIdRoute
  '/onboarding/organization': typeof OnboardingOrganizationRoute
  '/onboarding/pricing': typeof OnboardingPricingRoute
  '/onboarding/project': typeof OnboardingProjectRoute
  '/onboarding/waiting': typeof OnboardingWaitingRoute
  '/public/$domain': typeof PublicDomainRoute
  '/p/$projectId': typeof LayoutPProjectIdIndexRoute
  '/p/$projectId/funnels/$funnelId': typeof LayoutPProjectIdFunnelsFunnelIdRoute
  '/p/$projectId/user/$identifier': typeof LayoutPProjectIdUserIdentifierRoute
  '/p/$projectId/users/$userId': typeof LayoutPProjectIdUsersUserIdRoute
  '/p/$projectId/events': typeof LayoutPProjectIdEventsIndexRoute
  '/p/$projectId/funnels': typeof LayoutPProjectIdFunnelsIndexRoute
  '/p/$projectId/settings': typeof LayoutPProjectIdSettingsIndexRoute
  '/p/$projectId/users': typeof LayoutPProjectIdUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_layout': typeof LayoutRouteWithChildren
  '/billing': typeof BillingRoute
  '/redirect': typeof RedirectRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/invite/$token': typeof InviteTokenRoute
  '/mail/unsubscribe': typeof MailUnsubscribeRoute
  '/o/$organizationId': typeof OOrganizationIdRoute
  '/onboarding/organization': typeof OnboardingOrganizationRoute
  '/onboarding/pricing': typeof OnboardingPricingRoute
  '/onboarding/project': typeof OnboardingProjectRoute
  '/onboarding/waiting': typeof OnboardingWaitingRoute
  '/public/$domain': typeof PublicDomainRoute
  '/_layout/p/$projectId': typeof LayoutPProjectIdRouteWithChildren
  '/_layout/p/$projectId/': typeof LayoutPProjectIdIndexRoute
  '/_layout/p/$projectId/funnels/$funnelId': typeof LayoutPProjectIdFunnelsFunnelIdRoute
  '/_layout/p/$projectId/user/$identifier': typeof LayoutPProjectIdUserIdentifierRoute
  '/_layout/p/$projectId/users/$userId': typeof LayoutPProjectIdUsersUserIdRoute
  '/_layout/p/$projectId/events/': typeof LayoutPProjectIdEventsIndexRoute
  '/_layout/p/$projectId/funnels/': typeof LayoutPProjectIdFunnelsIndexRoute
  '/_layout/p/$projectId/settings/': typeof LayoutPProjectIdSettingsIndexRoute
  '/_layout/p/$projectId/users/': typeof LayoutPProjectIdUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/redirect'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/invite/$token'
    | '/mail/unsubscribe'
    | '/o/$organizationId'
    | '/onboarding/organization'
    | '/onboarding/pricing'
    | '/onboarding/project'
    | '/onboarding/waiting'
    | '/public/$domain'
    | '/p/$projectId'
    | '/p/$projectId/'
    | '/p/$projectId/funnels/$funnelId'
    | '/p/$projectId/user/$identifier'
    | '/p/$projectId/users/$userId'
    | '/p/$projectId/events'
    | '/p/$projectId/funnels'
    | '/p/$projectId/settings'
    | '/p/$projectId/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/redirect'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/invite/$token'
    | '/mail/unsubscribe'
    | '/o/$organizationId'
    | '/onboarding/organization'
    | '/onboarding/pricing'
    | '/onboarding/project'
    | '/onboarding/waiting'
    | '/public/$domain'
    | '/p/$projectId'
    | '/p/$projectId/funnels/$funnelId'
    | '/p/$projectId/user/$identifier'
    | '/p/$projectId/users/$userId'
    | '/p/$projectId/events'
    | '/p/$projectId/funnels'
    | '/p/$projectId/settings'
    | '/p/$projectId/users'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_layout'
    | '/billing'
    | '/redirect'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/_auth/signup'
    | '/invite/$token'
    | '/mail/unsubscribe'
    | '/o/$organizationId'
    | '/onboarding/organization'
    | '/onboarding/pricing'
    | '/onboarding/project'
    | '/onboarding/waiting'
    | '/public/$domain'
    | '/_layout/p/$projectId'
    | '/_layout/p/$projectId/'
    | '/_layout/p/$projectId/funnels/$funnelId'
    | '/_layout/p/$projectId/user/$identifier'
    | '/_layout/p/$projectId/users/$userId'
    | '/_layout/p/$projectId/events/'
    | '/_layout/p/$projectId/funnels/'
    | '/_layout/p/$projectId/settings/'
    | '/_layout/p/$projectId/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
  BillingRoute: typeof BillingRoute
  RedirectRoute: typeof RedirectRoute
  InviteTokenRoute: typeof InviteTokenRoute
  MailUnsubscribeRoute: typeof MailUnsubscribeRoute
  OOrganizationIdRoute: typeof OOrganizationIdRoute
  OnboardingOrganizationRoute: typeof OnboardingOrganizationRoute
  OnboardingPricingRoute: typeof OnboardingPricingRoute
  OnboardingProjectRoute: typeof OnboardingProjectRoute
  OnboardingWaitingRoute: typeof OnboardingWaitingRoute
  PublicDomainRoute: typeof PublicDomainRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/$domain': {
      id: '/public/$domain'
      path: '/public/$domain'
      fullPath: '/public/$domain'
      preLoaderRoute: typeof PublicDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/waiting': {
      id: '/onboarding/waiting'
      path: '/onboarding/waiting'
      fullPath: '/onboarding/waiting'
      preLoaderRoute: typeof OnboardingWaitingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/project': {
      id: '/onboarding/project'
      path: '/onboarding/project'
      fullPath: '/onboarding/project'
      preLoaderRoute: typeof OnboardingProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/pricing': {
      id: '/onboarding/pricing'
      path: '/onboarding/pricing'
      fullPath: '/onboarding/pricing'
      preLoaderRoute: typeof OnboardingPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/organization': {
      id: '/onboarding/organization'
      path: '/onboarding/organization'
      fullPath: '/onboarding/organization'
      preLoaderRoute: typeof OnboardingOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$organizationId': {
      id: '/o/$organizationId'
      path: '/o/$organizationId'
      fullPath: '/o/$organizationId'
      preLoaderRoute: typeof OOrganizationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail/unsubscribe': {
      id: '/mail/unsubscribe'
      path: '/mail/unsubscribe'
      fullPath: '/mail/unsubscribe'
      preLoaderRoute: typeof MailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_layout/p/$projectId': {
      id: '/_layout/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/p/$projectId'
      preLoaderRoute: typeof LayoutPProjectIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/p/$projectId/': {
      id: '/_layout/p/$projectId/'
      path: '/'
      fullPath: '/p/$projectId/'
      preLoaderRoute: typeof LayoutPProjectIdIndexRouteImport
      parentRoute: typeof LayoutPProjectIdRoute
    }
    '/_layout/p/$projectId/users/': {
      id: '/_layout/p/$projectId/users/'
      path: '/users'
      fullPath: '/p/$projectId/users'
      preLoaderRoute: typeof LayoutPProjectIdUsersIndexRouteImport
      parentRoute: typeof LayoutPProjectIdRoute
    }
    '/_layout/p/$projectId/settings/': {
      id: '/_layout/p/$projectId/settings/'
      path: '/settings'
      fullPath: '/p/$projectId/settings'
      preLoaderRoute: typeof LayoutPProjectIdSettingsIndexRouteImport
      parentRoute: typeof LayoutPProjectIdRoute
    }
    '/_layout/p/$projectId/funnels/': {
      id: '/_layout/p/$projectId/funnels/'
      path: '/funnels'
      fullPath: '/p/$projectId/funnels'
      preLoaderRoute: typeof LayoutPProjectIdFunnelsIndexRouteImport
      parentRoute: typeof LayoutPProjectIdRoute
    }
    '/_layout/p/$projectId/events/': {
      id: '/_layout/p/$projectId/events/'
      path: '/events'
      fullPath: '/p/$projectId/events'
      preLoaderRoute: typeof LayoutPProjectIdEventsIndexRouteImport
      parentRoute: typeof LayoutPProjectIdRoute
    }
    '/_layout/p/$projectId/users/$userId': {
      id: '/_layout/p/$projectId/users/$userId'
      path: '/users/$userId'
      fullPath: '/p/$projectId/users/$userId'
      preLoaderRoute: typeof LayoutPProjectIdUsersUserIdRouteImport
      parentRoute: typeof LayoutPProjectIdRoute
    }
    '/_layout/p/$projectId/user/$identifier': {
      id: '/_layout/p/$projectId/user/$identifier'
      path: '/user/$identifier'
      fullPath: '/p/$projectId/user/$identifier'
      preLoaderRoute: typeof LayoutPProjectIdUserIdentifierRouteImport
      parentRoute: typeof LayoutPProjectIdRoute
    }
    '/_layout/p/$projectId/funnels/$funnelId': {
      id: '/_layout/p/$projectId/funnels/$funnelId'
      path: '/funnels/$funnelId'
      fullPath: '/p/$projectId/funnels/$funnelId'
      preLoaderRoute: typeof LayoutPProjectIdFunnelsFunnelIdRouteImport
      parentRoute: typeof LayoutPProjectIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface LayoutPProjectIdRouteChildren {
  LayoutPProjectIdIndexRoute: typeof LayoutPProjectIdIndexRoute
  LayoutPProjectIdFunnelsFunnelIdRoute: typeof LayoutPProjectIdFunnelsFunnelIdRoute
  LayoutPProjectIdUserIdentifierRoute: typeof LayoutPProjectIdUserIdentifierRoute
  LayoutPProjectIdUsersUserIdRoute: typeof LayoutPProjectIdUsersUserIdRoute
  LayoutPProjectIdEventsIndexRoute: typeof LayoutPProjectIdEventsIndexRoute
  LayoutPProjectIdFunnelsIndexRoute: typeof LayoutPProjectIdFunnelsIndexRoute
  LayoutPProjectIdSettingsIndexRoute: typeof LayoutPProjectIdSettingsIndexRoute
  LayoutPProjectIdUsersIndexRoute: typeof LayoutPProjectIdUsersIndexRoute
}

const LayoutPProjectIdRouteChildren: LayoutPProjectIdRouteChildren = {
  LayoutPProjectIdIndexRoute: LayoutPProjectIdIndexRoute,
  LayoutPProjectIdFunnelsFunnelIdRoute: LayoutPProjectIdFunnelsFunnelIdRoute,
  LayoutPProjectIdUserIdentifierRoute: LayoutPProjectIdUserIdentifierRoute,
  LayoutPProjectIdUsersUserIdRoute: LayoutPProjectIdUsersUserIdRoute,
  LayoutPProjectIdEventsIndexRoute: LayoutPProjectIdEventsIndexRoute,
  LayoutPProjectIdFunnelsIndexRoute: LayoutPProjectIdFunnelsIndexRoute,
  LayoutPProjectIdSettingsIndexRoute: LayoutPProjectIdSettingsIndexRoute,
  LayoutPProjectIdUsersIndexRoute: LayoutPProjectIdUsersIndexRoute,
}

const LayoutPProjectIdRouteWithChildren =
  LayoutPProjectIdRoute._addFileChildren(LayoutPProjectIdRouteChildren)

interface LayoutRouteChildren {
  LayoutPProjectIdRoute: typeof LayoutPProjectIdRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutPProjectIdRoute: LayoutPProjectIdRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
  BillingRoute: BillingRoute,
  RedirectRoute: RedirectRoute,
  InviteTokenRoute: InviteTokenRoute,
  MailUnsubscribeRoute: MailUnsubscribeRoute,
  OOrganizationIdRoute: OOrganizationIdRoute,
  OnboardingOrganizationRoute: OnboardingOrganizationRoute,
  OnboardingPricingRoute: OnboardingPricingRoute,
  OnboardingProjectRoute: OnboardingProjectRoute,
  OnboardingWaitingRoute: OnboardingWaitingRoute,
  PublicDomainRoute: PublicDomainRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
