ALTER TABLE event ADD COLUMN IF NOT EXISTS `latitude` Nullable(Float32) DEFAULT NULL;
ALTER TABLE event ADD COLUMN IF NOT EXISTS `longitude` Nullable(Float32) DEFAULT NULL;

ALTER TABLE session ADD COLUMN IF NOT EXISTS `latitude` Nullable(Float32) DEFAULT NULL;
ALTER TABLE session ADD COLUMN IF NOT EXISTS `longitude` Nullable(Float32) DEFAULT NULL;

ALTER TABLE user ADD COLUMN IF NOT EXISTS `latitude` Nullable(Float32) DEFAULT NULL;
ALTER TABLE user ADD COLUMN IF NOT EXISTS `longitude` Nullable(Float32) DEFAULT NULL;